### ISSUE TITLE
Bulk move / copy files failed - improvement request

### ISSUE THREAD

**Issue by mix9311** [s3drive/app#29]
when I try to copy / move files to another Dict, no reaction on s3drive Android client, even in windows s3drive official website, keep operating and loading but still No progress, no results, stuck on that mobile file page...  but windows client seems to be fine and normal.. hope u fix it.

**Comment by tomekit** [comment]
As far I am concerned Storj doesn't support versioning.

Please make sure that your bucket supports versioning, otherwise please disable the: "Versioning" settings:

![Screenshot from 2023-05-01 21-18-53](https://user-images.githubusercontent.com/7759113/235514551-71e04f37-e98e-479b-a2ae-136cdd93d921.png)
![Screenshot from 2023-05-01 21-18-14](https://user-images.githubusercontent.com/7759113/235514556-071340a8-aada-47e7-b224-fe6a833a14dd.png)

Can you please let me know if this resolved your issue?

As for the Chinese language, yes we will be looking into translation the S3Drive into multiple languages in the future: https://s3drive.canny.io/feature-requests/p/add-translation-strings

**Comment by tomekit** [comment]
How many files you try to copy/move at once? If it's a folder how many (approximately) files you try to copy/move during single operation?
S3 protocol doesn't support bulk copy/move and every single file operation issues at least one S3 request. We will be improving that by parallelizing outgoing requests, but that's not yet ready.

As for Storj not showing the stats, it is because we get these numbers from Versioning API which isn't supported by Storj. We will improve this by implementing fallback to Listing API for providers which doesn't support Versioning API.

**Comment by tomekit** [comment]
We'll be improving this by:
- introducing parallelized requests,
- introducing file operation monitor with progress bar which will provide live results,
- implementing cancel/abort button to forcefully stop the operation

**Comment by tomekit** [comment]
Moved here: https://s3drive.canny.io/feature-requests/p/improve-copymove-resilience-and-performance
