### ISSUE TITLE
Android client crashes

### ISSUE THREAD

**Issue by mix9311** [s3drive/app#33]
When uploading files using the Android client, it still crashes and returns directly to the desktop. I am very sad. But it is already the latest version 1.2.10 I don't know what to do!

**Comment by tomekit** [comment]
Thanks for report. Are you using E2E encryption? 
Can you please long tap on the version number and see if there is any error or warning in Logs?
Did you find any pattern when it crashes and when it doesn't crash?
Can you try uploading single file instead of multiple and see if it helps?
What's your mobile phone model and how much RAM you have

I would appreciate if you could provide me those details, so I can troubleshoot this issue for you. Thanks !
