### ISSUE TITLE
Improvement: Media backup WLAN only

### ISSUE THREAD

**Issue by Morethanevil** [s3drive/app#39]
Add an option to use the automatic backup only when WLAN connection is used to save mobile traffic

Bonus: add an option to select a specific bucket for backups instead of the currently selected one. Maybe with a self selected path too

**Comment by tomekit** [comment]
Thank you for these ideas. Even though WLAN constraint is part of our development plan we haven't mentioned that externally, so I've created a roadmap item for that: https://s3drive.canny.io/feature-requests/p/upload-constraints-only-wifi-only-charger-battery-not-low

The custom backup location feature was also just added: https://s3drive.canny.io/feature-requests/p/allow-specifying-custom-backup-location

Support for multiple buckets operations (not just the selected one) was requested already and waits for execution: https://s3drive.canny.io/feature-requests/p/support-using-multiple-accounts-at-once
This one would require bigger changes, so it's hard to give the exact ETA at this stage.

**Comment by tomekit** [comment]
Backup constraints (https://s3drive.canny.io/feature-requests/p/upload-constraints-only-wifi-only-charger-battery-not-low) are now implemented for both in-app and background backup in our recent 1.6.0 release.
Note: Battery not low option is available only for Android.

Support for multiple simultaneous accounts operation is currently in the planning phase (https://s3drive.canny.io/feature-requests/p/support-simultaneous-accounts-operation), however because of a relatively big scope of this work it's likely that we won't be able to deliver it before Q1 2024
