### ISSUE TITLE
File uploaded from rclone to s3drive and from s3drive to rclone are not decryptable

### ISSUE THREAD

**Issue by Koltsz** [s3drive/app#43]
Hi.
Im using the Android version 1.5.0 I have paid for the filename encryption.

Could you help with what I could be missing please? I have set up rclone with the same password, enabled filename, folder and file encryption I have said no to salting the password and I am unable to decrypt files uploaded from s3Drive that use the same password.

This goes for me uploading files from rclone and trying to view them on s3Drive.

Could you point me into the right direction please?

**Comment by tomekit** [comment]
Hi, what version of Rclone are you using? Can you post your config of `remote` and `crypt`? You can export it using: `rclone config dump` (please remove sensitive details, that is at least `password` and `secret_access_key`).

This is the config that we support and tested Rclone and S3Drive together:
```
# Obscure password
echo "YourPlaintextPassword" | rclone obscure -
```

```
# Add it to Rclone config, config file location: `rclone config file`
[s3drive_remote]
type = s3
provider = Other
access_key_id = <access_key_id>
secret_access_key = <secret_access_key>
endpoint = <endpoint>
region = <region>

[s3drive_crypt]
type = crypt
filename_encoding = base64
remote = s3drive_remote:<bucket_name>
password = <obscuredPassword>
filename_encryption = standard
directory_name_encryption = true
suffix = none
```

**Comment by Koltsz** [comment]
Hi,
Thanks for the quick reply

Im using rclone v1.63.1

the config dump is:

`{
    "minIO": {
        "access_key_id": "***",
        "endpoint": "***",
        "location_constraint": "eu-west-2",
        "provider": "Minio",
        "region": "eu-west-2",
        "secret_access_key": "***",
        "type": "s3"
    },
    "minIO_crypt": {
        "password": "***",
        "remote": "minIO:main/crypt",
        "type": "crypt"
    }
}`

**Comment by tomekit** [comment]
Thanks for posting your config.

In your config you use the `base32` default encoding, whereas S3 supports `base64` and that's what we use with S3Drive: https://rclone.org/crypt/#crypt-filename-encoding

We've made rest parameters explicit, but you shouldn't need all of them as they're the same as the current Rclone defaults.

If you ever decide to not use filename encryption you'll need the: `suffix: none`, because by default Rclone would append `.bin` suffix and we don't really want this behavior on the S3Drive side.
It shouldn't be required in your current case though, as it seems you're using: `standard` (default) filepath encryption.
https://rclone.org/crypt/#crypt-filename-encryption
https://rclone.org/crypt/#crypt-suffix

Please let me know if setting encoding to `base64` resolved your issue.

**Comment by Koltsz** [comment]
OK this is what I have now and it works from uploading from rclone and s3drive can read it
but when I upload a file to s3drive , rclone is unable to ls it, 

`rclone ls minIO_crypt:main` doesn't show anything

[minIO]
type = s3
provider = Minio
access_key_id = ***
secret_access_key = ***
endpoint = ***
region = eu-west-2
location_constraint = eu-west-2

[minIO_crypt]
type = crypt
remote = minIO:main
password = ***
filename_encoding = base64
filename_encryption = standard
directory_name_encryption = true
suffix = none

**Comment by Koltsz** [comment]
scrap that it works !

just needed to make sure I put the file in the correct folder so rclone can see it

Thank you for all of your help! app is great by the way
