### ISSUE TITLE
Mac App Store Version Will Not Launch

### ISSUE THREAD

**Issue by jbosse** [s3drive/app#54]
When I launch the app:
![image](https://github.com/s3drive/app/assets/119121/fafd734b-0632-423c-878b-5f27567e3855)

This sucks. The app did what I needed it to do. Fine move on past the App Store, but to lock me out of the app is incredibly frustrating.

**Comment by tomekit** [comment]
Hi @jbosse,

We will aim to fix that over the next couple days. In the meantime (if possible) please use our up to date DMG release: https://docs.s3drive.app/install/#dmg-package

We aren't releasing as frequently on Mac Store, because we're constantly dealing with some new challenges with this distribution method.
Our most recent release was rejected:
![Screenshot from 2024-05-17 20-05-34](https://github.com/s3drive/app/assets/7759113/89d0c459-5dcc-44ed-92cc-1b5701d06d32)

and given the fact that most of our users prefer using .DMG anyway, we haven't dedicated enough time to resolve these issues.

Sorry for that. I will let you know once this gets resolved. Thank you for your report !

**Comment by jbosse** [comment]
@tomekit I very much understand not wanting to be in the App Store anymore. I was just incredible frustrated by the experience. It would be better to remove the app entirely than redirect a user to download a different installer. I'm surprised that update made it past app review because that is the kind of thing Apple seems to hate. Plus it seemed very suspicious to me and raised red flags for software I wanted to run on my company laptop.

**Comment by tomekit** [comment]
Hi @jbosse,

> I very much understand not wanting to be in the App Store anymore.

It's quite the opposite, we want to be present on as many platforms / stores as possible. Every user is different and comes from a different place.

> I was just incredibly frustrated by the experience.

I am sorry to hear that. As a tiny line of defense, we're also quite frustrated from our developer's perspective, dealing with the technological legacies and review bureaucracy and wasting our time that could be well spent improving the product.
Our most recent update to macOS was rejected yet again today:
![Screenshot from 2024-05-18 18-29-50](https://github.com/s3drive/app/assets/7759113/5de29123-6d9e-420b-96b6-5eff8453bbb5)
because apparently app doesn't start properly, but that's not what we and our users are finding.

> It would be better to remove the app entirely than redirect a user to download a different installer. 

I agree with you and we've tried that, but it's app to Apple to decide and their stance it quite clear. Once app is uploaded to App Store it can't be removed without removing corresponding iOS version: https://forums.developer.apple.com/forums/thread/651148 

> I'm surprised that update made it past app review because that is the kind of thing Apple seems to hate. Plus it seemed very suspicious to me and raised red flags for software I wanted to run on my company laptop.

That's the mechanism that we've mentioned in our ToS which you've had to accept before using the app. Since development on the app is very active with frequent releases every couple weeks at max, we impose a validity on the app version, so we can "force" (we don't like that word though) our users to upgrade, before their version is too old to update smoothly.

Maintaining support for very old versions puts too much strain on our resources. At some point will either extend validity to longer periods (e.g. introduce LTS versions) or remove it completely. Currently it's something that allows us to dynamically improve the ecosystem, performance and security without having to maintain support for legacy version upgrades.

Don't get us wrong, as much as we would like to have most recent version available on the App Store, it's actually not entirely on us. 

I will try to update you once we get past the review. At the moment we're awaiting Apple's turn.








Our update

**Comment by tomekit** [comment]
Hi @jbosse,

Our most recent version got approved on App Store. Thank you for your patience.

I am going to close this issue for now, but if there is anything to sort out, please comment so I can reopen.

App store: 
https://apps.apple.com/lv/app/s3drive-cloud-storage/id1665135106

**Comment by jbosse** [comment]
Fantastic! Now I can get back to fixing my bug that I need the app to help me troubleshoot 😀. Thanks for your patience and quick response!

-Jimmy
